/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.ShopBuilder;

import java.awt.Button;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Prashant
 */
public class AddItems extends javax.swing.JFrame {
    
    int u_id;
    ResultSet rs;
    String name;
    String address;
    DefaultTableModel dm;
    DbConnect con;

    /**
     * Creates new form AddItems
     */
    public AddItems(int id) {
        u_id = id;
        initComponents();
        this.setLocationRelativeTo(null);
        con = new DbConnect();      
        ResultSet rs2 = con.searchById(id);
        try{
            if(rs2.next()){
                name = rs2.getString("NAME");
                address = rs2.getString("ADDRESS");
                cust_name.setText(name);
                cust_address.setText(address);
            }
        }catch(Exception e){
            System.out.println(e);
        }
        ResultSet rsI = con.fetchItems();
        try{
            if(rsI.next()==false){
                System.out.println("No Items Added!");
            }else{
                do{
                    item_name.addItem(rsI.getString("itemName"));
                }while(rsI.next());
            }
        }catch(Exception e){
            System.out.println(e);
        }
        setTable();
        this.getRootPane().setDefaultButton(add_to_basket);
    }

    private AddItems() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cust_name = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cust_address = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        itme_quantity = new javax.swing.JTextField();
        add_to_basket = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        all_items_purchased = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        close_additems = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        payable_amount = new javax.swing.JLabel();
        item_name = new javax.swing.JComboBox<>();
        item_price = new javax.swing.JLabel();
        custom_tools = new javax.swing.JToolBar();
        search_by_date = new javax.swing.JButton();
        search_by_item = new javax.swing.JButton();
        search_by_id = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Customer");

        cust_name.setText("cust_name");

        jLabel3.setText("Address");

        cust_address.setText("cust_address");

        jLabel5.setText("Item Name");

        jLabel6.setText("Price");

        jLabel7.setText("Quantity");

        add_to_basket.setText("Add to Basket");
        add_to_basket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_to_basketActionPerformed(evt);
            }
        });

        all_items_purchased.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(all_items_purchased);

        jLabel10.setText("Final Basket");

        close_additems.setText("Close");
        close_additems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_additemsActionPerformed(evt);
            }
        });

        jLabel2.setText("Final Payable amount");

        payable_amount.setText("payable_amt");

        item_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_nameActionPerformed(evt);
            }
        });

        item_price.setText("Item Price");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cust_name)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cust_address)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10)
                                        .addGap(168, 168, 168))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addGap(33, 33, 33)
                                .addComponent(payable_amount)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(add_to_basket))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(34, 34, 34)
                                        .addComponent(itme_quantity))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(item_name, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(item_price))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(close_additems)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cust_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cust_address)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(item_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(item_price))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(itme_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(add_to_basket))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(payable_amount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(close_additems)
                .addGap(7, 7, 7))
        );

        custom_tools.setRollover(true);

        search_by_date.setText("Search by Date");
        search_by_date.setFocusable(false);
        search_by_date.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        search_by_date.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        search_by_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_by_dateActionPerformed(evt);
            }
        });
        custom_tools.add(search_by_date);

        search_by_item.setText("Search by Item");
        search_by_item.setFocusable(false);
        search_by_item.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        search_by_item.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        search_by_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_by_itemActionPerformed(evt);
            }
        });
        custom_tools.add(search_by_item);

        search_by_id.setText("Search by ID");
        search_by_id.setFocusable(false);
        search_by_id.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        search_by_id.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        search_by_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_by_idActionPerformed(evt);
            }
        });
        custom_tools.add(search_by_id);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(custom_tools, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(custom_tools, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_additemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_additemsActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_close_additemsActionPerformed

    private void add_to_basketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_to_basketActionPerformed
        // TODO add your handling code here:
        DbConnect con = new DbConnect();
        String item = item_name.getSelectedItem().toString();
        float price = con.getItemPrice(item);
        //item_price.setText(Float.toString(price));
        int quant = Integer.parseInt(itme_quantity.getText());
        float tot = price*quant;
        if(name!=null){
            con.addItemsInPurchase(u_id, item, price, quant, tot, name);
        }
        System.out.println(item+price+quant+tot+name+u_id);
        System.out.println("Items Added Successfully!!");
        //item_name.setText("");
        //item_price.setText("");
        itme_quantity.setText("");
        setTable();
        System.out.println("Calling getData");
        getData();
        
    }//GEN-LAST:event_add_to_basketActionPerformed

    private void search_by_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_by_dateActionPerformed
        new SearchByDate().setVisible(true);
    }//GEN-LAST:event_search_by_dateActionPerformed

    private void item_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_nameActionPerformed
        // TODO add your handling code here:
        String item = item_name.getSelectedItem().toString();
        DbConnect con = new DbConnect();
        float price = con.getItemPrice(item);
        item_price.setText(Float.toString(price));
    }//GEN-LAST:event_item_nameActionPerformed

    private void search_by_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_by_itemActionPerformed
        // TODO add your handling code here:
        new SearchByItem().setVisible(true);
    }//GEN-LAST:event_search_by_itemActionPerformed

    private void search_by_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_by_idActionPerformed
        // TODO add your handling code here:
        new SearchById().setVisible(true);
    }//GEN-LAST:event_search_by_idActionPerformed

    private void setTable(){        
        dm = new DefaultTableModel(0,0);
        String s[] = new String[]{"Cust_Name","Item_Name","Price","Quantity","Total"};
        dm.setColumnIdentifiers(s);
        all_items_purchased.setModel(dm);
    }
    
    private void getData(){
        DbConnect con = new DbConnect();
        ResultSet rs;
        rs = con.getTableData(u_id);
        float total_price = 0;
        System.out.println("data recieved for "+u_id);
        try{
            System.out.println("inside try.."+rs);            
            while(rs.next()){
                System.out.println("Extracting from Resultset "+rs.getString("cust_name"));
                String c_name = rs.getString("cust_name");
                String i_name = rs.getString("itemName");
                float price = rs.getFloat("price");
                //float price = Float.parseFloat(rs.getString("price"));
                int quant = Integer.parseInt(rs.getString("quant"));
                float tot = Float.parseFloat(rs.getString("tot"));
                Vector<String> vector = new Vector<>();
                vector.add(c_name);
                vector.add(i_name);
                vector.add(Float.toString(price));
                vector.add(Integer.toString(quant));
                vector.add(Float.toString(tot));
                System.out.println(c_name+i_name+price+quant+tot);
                dm.addRow(vector);
                total_price = total_price + tot;
            }
        }catch(Exception e){
            System.out.println(e);
        }
        payable_amount.setText(Float.toString(total_price));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddItems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_to_basket;
    private javax.swing.JTable all_items_purchased;
    private javax.swing.JButton close_additems;
    private javax.swing.JLabel cust_address;
    private javax.swing.JLabel cust_name;
    private javax.swing.JToolBar custom_tools;
    private javax.swing.JComboBox<String> item_name;
    private javax.swing.JLabel item_price;
    private javax.swing.JTextField itme_quantity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel payable_amount;
    private javax.swing.JButton search_by_date;
    private javax.swing.JButton search_by_id;
    private javax.swing.JButton search_by_item;
    // End of variables declaration//GEN-END:variables
}
